// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: owVdPvEphTbmsFvPUSwECY
// Component: Z_wKemL1bX2Un
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: BaUbUZuz8l79s/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: 38wpV2hoT24T/component
import ProductCard from "../../ProductCard"; // plasmic-import: jkTmUNlzZfjqKf/component
import Ratings from "../../Ratings"; // plasmic-import: Wxr8hD3Wuh02fH/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: PDi4XCOwFc7w_/component
import BlogPost from "../../BlogPost"; // plasmic-import: V88Dlg9S4dXgNr/component
import Footer from "../../Footer"; // plasmic-import: WnTO2axET2_0X/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: uYbqYp8q9yY0/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: owVdPvEphTbmsFvPUSwECY/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: Z_wKemL1bX2Un/css

import arrivals1N7PdnyMy09It from "./images/arrivals1.png"; // plasmic-import: N7Pdny-MY09IT/picture
import arrivals2MWnVd4QFtFcQz from "./images/arrivals2.png"; // plasmic-import: mWnVD4qFtFcQZ/picture
import arrivals3ZxKm2PxmlQqzh from "./images/arrivals3.png"; // plasmic-import: ZXKm2pxmlQQZH/picture
import arrivals4477SIa2G1CaZ from "./images/arrivals4.png"; // plasmic-import: 477SIa2g1ca-Z/picture
import arrivals5RcV5XeZd0Vqm from "./images/arrivals5.png"; // plasmic-import: rcV5xeZD0_Vqm/picture
import arrivals6Dzsk5N31DjoSo from "./images/arrivals6.png"; // plasmic-import: Dzsk5n31djoSO/picture
import arrivals7IHjzDywcvkPj from "./images/arrivals7.png"; // plasmic-import: i-HJZDywcvkPj/picture
import arrivals8J25HKGrDlko5 from "./images/arrivals8.png"; // plasmic-import: J2-5hKGrDLKO5/picture
import f1FuvbI3Cdfiwxn from "./images/f1.jpeg"; // plasmic-import: FuvbI3CDFIWXN/picture
import f2NfJtDlKkGve5L from "./images/f2.jpeg"; // plasmic-import: NFJtDLKkGve5l/picture
import f33PqETtT53ZXj from "./images/f3.jpeg"; // plasmic-import: -3PqETtT53zXj/picture
import f4KjpgkKKnEsCiK from "./images/f4.jpeg"; // plasmic-import: KjpgkKKnEsCiK/picture
import b1OxVhIzRlUZpTi from "./images/b1.jpeg"; // plasmic-import: oxVHIzRlUZpTi/picture
import b264YjXBPyahM1 from "./images/b2.jpeg"; // plasmic-import: 64YjX_BPyahM1/picture
import b3JcQtNhQc38SlZ from "./images/b3.jpeg"; // plasmic-import: JCQtNHQc38SlZ/picture
import adidasOjSq28KmKMy from "./images/adidas.png"; // plasmic-import: -OjSq28KmK_My/picture
import hm1ZrpYdzBrD3Dk from "./images/hm.png"; // plasmic-import: 1zrpYDZBrD3Dk/picture
import kappaIgNicOyZb5T2 from "./images/kappa.png"; // plasmic-import: igNIC_OyZb5t2/picture
import lacosteDDTrkKFn4Epgd from "./images/lacoste.png"; // plasmic-import: dDTrkKFn4EPGD/picture
import levis2JkJyO2Ea1G7 from "./images/levis.png"; // plasmic-import: 2JKJyO2EA1_g7/picture

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  productCarousel?: p.Flex<typeof ProductCarousel>;
  featureItem?: p.Flex<typeof FeatureItem>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  dataFetches?: PlasmicHome__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.box__nrQ42)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />

            <ProductCarousel
              data-plasmic-name={"productCarousel"}
              data-plasmic-override={overrides.productCarousel}
              className={classNames("__wab_instance", sty.productCarousel)}
            />

            <div className={classNames(defaultcss.all, sty.box__l7Cfj)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__hW9Es
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__quEgC)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__ohxHi)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__iq62W)}
                    height={120 as const}
                    role={"img"}
                    src={arrivals1N7PdnyMy09It}
                    width={120 as const}
                  />
                }
                onSale={"onSale" as const}
                price={"$65.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__eXtV)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__rfF1F)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__z5E0J)}
                    height={116 as const}
                    role={"img"}
                    src={arrivals2MWnVd4QFtFcQz}
                    width={138 as const}
                  />
                }
                onSale={"onSale" as const}
                price={"$80.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__zg8Uf)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Single Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__fx484)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__vvXeb)}
                    height={116 as const}
                    role={"img"}
                    src={arrivals3ZxKm2PxmlQqzh}
                    width={135 as const}
                  />
                }
                price={"$40.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__ztetj)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__gz8Fq)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__qifEi)}
                    height={130 as const}
                    role={"img"}
                    src={arrivals4477SIa2G1CaZ}
                    width={100 as const}
                  />
                }
                onSale={"onSale" as const}
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__xqg7Z)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Stylish Chair"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box___2WTw)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard___8M8K)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___389LY)}
                    height={127 as const}
                    role={"img"}
                    src={arrivals5RcV5XeZd0Vqm}
                    width={105 as const}
                  />
                }
                price={"$120.00"}
                title={"Modern Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__mZKqI)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__duIG)}
                    height={123 as const}
                    role={"img"}
                    src={arrivals6Dzsk5N31DjoSo}
                    width={176 as const}
                  />
                }
                onSale={"onSale" as const}
                price={"$140.00"}
                title={"Mapple Wood Dinning Table"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__s1Tgi)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3DAo)}
                    height={120 as const}
                    role={"img"}
                    src={arrivals7IHjzDywcvkPj}
                    width={160 as const}
                  />
                }
                onSale={"onSale" as const}
                price={"$90.00"}
                title={"Arm Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__uxhh7)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__lYeSd)}
                    height={101 as const}
                    role={"img"}
                    src={arrivals8J25HKGrDlko5}
                    width={191 as const}
                  />
                }
                price={"$140.00"}
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__l6EGs
                    )}
                  >
                    {"Wooden Bed"}
                  </div>
                }
              />
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(defaultcss.all, sty.box___8Ez82)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__mNj9
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__g0Nhm)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__wg6WF)}
                price={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___2Pmc
                    )}
                  >
                    {"$160.00"}
                  </div>
                }
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__f6LXh)}
                    numReviews={"(12 Review)"}
                    stars={"two" as const}
                  />
                }
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__eigQl
                    )}
                  >
                    {"Designed Sofa"}
                  </div>
                }
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__zWweT)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ckYx)}
                    height={310 as const}
                    role={"img"}
                    src={f2NfJtDlKkGve5L}
                    width={270 as const}
                  />
                }
                price={"$200.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__lEw3A)}
                    stars={"four" as const}
                  />
                }
                title={"Dining Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__sll7D)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__yY9Nq)}
                    height={310 as const}
                    role={"img"}
                    src={f33PqETtT53ZXj}
                    width={270 as const}
                  />
                }
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__rR7Z)}
                    numReviews={"(23 Review)"}
                    stars={"five" as const}
                  />
                }
                title={"Chair and Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__tSeQ)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__c54Ek)}
                    height={310 as const}
                    role={"img"}
                    src={f4KjpgkKKnEsCiK}
                    width={270 as const}
                  />
                }
                price={"$299.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___3Vpho
                    )}
                    numReviews={"(35 Review)"}
                  />
                }
                title={"Modern Arm Chair"}
                withReviews={"withReviews" as const}
              />
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.box__wcoh0)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__whjCg
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__dFzQt)}
            >
              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__msAn8)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__sqBt8)}
                    height={250 as const}
                    role={"img"}
                    src={b1OxVhIzRlUZpTi}
                    width={370 as const}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__kB284)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__t4XpA)}
                    height={250 as const}
                    role={"img"}
                    src={b264YjXBPyahM1}
                    width={370 as const}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost___4IdV)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__tLaRj)}
                    height={250 as const}
                    role={"img"}
                    src={b3JcQtNhQc38SlZ}
                    width={370 as const}
                  />
                }
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__lgoMr)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___34YpO)}
                height={60 as const}
                role={"img"}
                src={adidasOjSq28KmKMy}
                width={90 as const}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___0ErXx)}
                height={60 as const}
                role={"img"}
                src={hm1ZrpYdzBrD3Dk}
                width={91 as const}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__ac30X)}
                height={60 as const}
                role={"img"}
                src={kappaIgNicOyZb5T2}
                width={98 as const}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___0Fh9K)}
                height={60 as const}
                role={"img"}
                src={lacosteDDTrkKFn4Epgd}
                width={124 as const}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__eOelN)}
                height={60 as const}
                role={"img"}
                src={levis2JkJyO2Ea1G7}
                width={125 as const}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  productCarousel: typeof ProductCarousel;
  featureItem: typeof FeatureItem;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHome__Fetches;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
